### ISSUE TITLE
Sprint #1 task list

### ISSUE THREAD

**Issue by theZalmanian** [theZalmanian/TeamGecko#1]
## Requirements for Sprint 1:
- [x] **Add consistent styling across all Sprint 1 pages**
- [x] Setup client color palatte (different from gecko color palatte)
- [x] Link all html files to the same css file
- [x] Implement dark mode (light mode default)
- [x] Create pages with a mobile-first design :white_check_mark: 
- [x] All pages should have the site navigation at top

### **Requirements Page**:
- [x] Recreate table in document
- [x] Make "or" options visually distinct
- [x] Mobile: Only title is visible, dropdown to display info

### **Experience**:
- [x] Recreate survey form from PDF
- [x] Implement 1 - 5 rating scale
- [x] First 6 items are required *, 7 and 8 are optional
- [x] Submit form data to vardump.php (inputs should have names)

### **Contact Form**:
- [x] Name (required), Email (required), Phone, Message (required)
- [x] Submit form data to vardump.php (inputs should have names)
