### ISSUE TITLE
Sprint 4 Task List

### ISSUE THREAD

**Issue by theZalmanian** [theZalmanian/TeamGecko#30]
### Before the sprint:
- [x] Copy over Sprint 3 pages & create new ones necessary for Sprint 4
- [x] Create new css file for sprint 
- [x] Update links on gecko pages 
- Implement any client feedback if given (not yet)

### Sprint workload:
- [x] Add navigation to admin pages
- [x] #31
- [x] #32
- [x] #33
- [x] #34 
- [x] #35

### General improvements:
- [x] #36
- [x] #37
- [x] #38
