### ISSUE TITLE
Sprint 5 Task List

### ISSUE THREAD

**Issue by theZalmanian** [theZalmanian/TeamGecko#41]
### Before the sprint:
- [x] Copy over Sprint 4 pages & create new ones necessary for Sprint 5
- [x] Create new CSS file for sprint 
- [x] Create new navigation layout page for sprint
- [x] Update links on gecko home page

### Should be done by now:
- Requirements page with strong mobile and desktop styling, ability to edit the page 
  - #20
- Experience form with a high concern for usability 
  - #19
- Experience responses are stored, visible, searchable and/or sortable 
  - #32
- Dark mode that persists through the website 
  - #33

### Admin and Login:
- [x] #42
- [x] #43
- [x] Hide a link to the login page in the footer of all pages in the website

### Our decided items:
- [x] #44
- [x] #45
- [x] #46

### General improvements:
- [x] #36
- [x] #37
- [x] #38
